src/string.c
errno.h is an external dependency which causes compilation to fail:
gcc -Wall -c -ffreestanding -m32 -march=i386 string.c -o string.o
In file included from /usr/include/features.h:389:0,
from /usr/include/errno.h:28,
from string.c:8:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
compilation terminated.
Makefile:19: recipe for target 'string.o' failed
make: *** [string.o] Error 1
This is caused by missing 32-bit header support on my system.
Fortunately stdarg.h (the only external header) is usable.
=> Remove unused header.

src/ata.c
Modify handling of ATAPI devices -- do not check for the RDY bit in status when performing IDENTIFY or SCSI_READ.  Also in configuration, test for presence of controller by comparing status bit to 0xff.
Closes #2
=> Fix ATAPI Probes

src/pic.c
This fixes an issue with the creation of an interrupt mask
for the slave PIC. The IRQ value being used to generate the mask
was not relative to the slave, and so resulted in shifting values
too far, and generating clear masks (all 1's). This disabled all
interrupts for the slave PIC instead of enabling certain ones.
=> Fixed PIC Slave bug

src/interrupt.c
Simply added '\f's to the start of `console_printf`s in `interupt.c`.
=> Errors now on own screen, fixes #16

src/ata.c
This is the change that I mentioned in our discussion where cdromfs halts indefinitely.
Let me know if that looks okay.
=> ata.c: unset ata_interrupt_active flag on ata_interrupt complete

src/string.c
Instead of letting f (the place value iterator) get larger than i (the
subject to be printed) and protentially overflow, stop the loop when f
is at exactly the largest place value the number has, rather than one
place value greater.
=> string: prevent integer overflow in printf_putint

src/kernelcore.S
For VBE 2.0 and onward, it is not mandatory to support the numbered VBE modes. VMware Player 12 does not seem to support the currently implemented video modes, so as a temporary work around I found one that it does support and added it after the current default 640x480 video mode. Going forward it might be wise to try enumerating the supported video modes and choosing one of them rather than just trying different numbered modes.
=> Added new fall-through low color video mode so VMware can boot

src/Makefile, src/cdromfs.c, src/cdromfs.h, src/interrupt.c, src/main.c, src/process.c, src/process.h, src/syscall.h, src/syscall_handler.c, src/test.c
Implements system call `sys_run` which creates a child process and loads an executable into it.
`main` expects the CDROM to be mounted as unit 1 and loads the program `TEST.EXE` from it.
This simple program exercises the `debug` and `exit` system calls.
Ideally, `sys_run` would not invoke the cdrom directly but instead go through an abstract filesystem interface.
=> Execute Simple User Program From CDROM

src/process.c, src/process.h, src/syscall.h, src/syscall_handler.c, src/syscalls.c, src/syscalls.h
I added the getpid system call.
The only reason this is marked WIP is because in linux the function `getpid` is cached, and was wondering if we'd want ours cached too.
Would something like
```
int getpid() {
static int cache = 0;
return cache? (cache) : (cache=syscall( SYSCALL_GETPID, 0, 0, 0, 0, 0 ));
}
```
work here, and should something like that be implemented?
=> Added getpid syscall

src/kernelcore.S
Based off of information found at http://wiki.osdev.org/A20_Line#Enabling -
I believe this fixes #60, I tested it with each resolution in `kernelcore.S` using VirtualBox.
=> Added code to enable the A20 address line

README.md
From the [OSDev Wiki page](http://wiki.osdev.org/GCC_Cross-Compiler#Binutils) on building GCC:
`--with-sysroot tells binutils to enable sysroot support in the cross-compiler by pointing it to a default empty directory. By default the linker refuses to use sysroots for no good technical reason, while gcc is able to handle both cases at runtime.`
=> Added --with-sysroot to binutils ./configure flags

src/ata.c
ATA I/O is now always blocking PIO.
=> Disable interrupt waiting due to unsolved race condition.

src/syscall_handler.c
Comment for sys_process_run used the old name of the function.
=> Fix comment typo

src/syscalls.c, src/syscalls.h
`process_run` was declared as `run`, which is fixed.
The return type of `keyboard_read_char` was also incorrect, which is fixed.
=> Fix process_run and keyboard_read_char

src/kshell.c
Run and start, if ran without arguments, called list_dir.  This is a typo, it should be printf.
=> Correct kshell 

src/cdromfs.c
Addresses #93.
`cdromfs.c`'s read dir and dirent lookup now make files appear lowercase when using the cdromfs filesystem.
Documentation will be added at merge so that the documentation isn't out of sync with master.
=> Add lowercase cdromfs files, in appearance

src/pagetable.c
I think this typo prevents many pages from being correctly freed.
=> Fix pagetable_delete typo

src/cdromfs.c
Addresses #120.  As [this resource](http://alumnus.caltech.edu/~pje/iso9660.html) notes, the current directory (".") and parent directory ("..") are represented as the ident being 0 and 1, respectively.
We handle this correctly in `cdrom_dirent_read_dir`, but not in `cdrom_dirent_lookup`, which this PR addresses.
=> Correct name and ident comparison in cdrom_dirent_lookup

src/kshell.c, src/usrshell.c
A collection of small improvements for the usability of kshell and usrshell
- usrshell's prompt is now `u$ `, so it's harder to get confused if you're using usrshell or kshell.
- usrshell now tracks if a namespace has been chosen, so operations requiring one don't error.
- More error checking in usrshell.
- kshell now checks if the running the program worked, so it doesn't hang waiting for a nonexistent program.
- usrshell's run and start now actually pass arguments.
=> Usability improvments for kshell and usrshell

src/fs_space.c
Currently a process can escape its ns_root by doing chdir'ing into something like `./././././../..`, since each "." is counted as going lower in the filesystem tree.
=> Handle '.' accurately

kernel/device.c, kernel/device.h
(Subsetting will happen at the higher level of kernel objects.)
=> Removed unused device subset functionality.

.gitignore, Makefile.config, build-cross-compiler.sh, library/Makefile
Building the cross-compiler and building Basekernel with a cross-compiler should now be (mostly) platform-independent and works on macOS. On Linux (Debian 9 stretch), build-cross-compiler.sh still fails trying to configure gcc:
```
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/tmp.Ifz6SIKmzO/gcc-8.2.0-elf-objs/gcc':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
Makefile:4200: recipe for target 'configure-gcc' failed
make: *** [configure-gcc] Error 1
```
=> Fixed bugs in build process using cross-compiler

build-cross-compiler.sh
Adds steps to download and install the cross-platform version of gdb (i686-elf-gdb) to the build-cross-compiler.sh script so that gdb can be used to debug basekernel
=> Add i686-elf-gdb to cross compiler script

kernel/kevinfs.c
Fix kevinfs_read_dir to return a null-separated array of entry filenames instead of a space-separated array
=> Fix kevinfs_read_dir to separate entry names with \0 instead of space.

include/library/syscalls.h
At some point, the function declaration for read_nonblock in syscalls.h was lost. This is a simple PR adding it back in.
=> Missing Function Declaration for read_nonblock in syscalls.h

kernel/mouse.c
Note that `(status&PS_STATUS_IBF)` will never be equal to one b/c `PS_STATUS_IBF` is `0x02`.
=> Fix logic error in mouse handler.

Makefile.config, kernel/ata.c, kernel/kevinfs.c
I get a bunch of fiddly warnings when compiling on gcc 4.8.5.
I propose we set the code standard to GNU C99.
(And also fix up some nested initializer warnings.)
Does this work for everyone else?
=> Fixed up to GNU99 Standard

kernel/process.c, kernel/process.h, kernel/syscall_handler.c, user/exctst.c
Because the arguments must by copied from one address space to another,
the only safe way to do it is to first duplicate into kernel space,
and then copy into the child process when its address space is active.
=> Fix program argument handling.

include/kernel/ktypes.h, include/library/objno.h, kernel/kobject.h, library/Makefile, library/objno.c
Exposed kobject types enum to #include space and implemented library function for converting to string.
=> Object type to string

kernel/kobject.c
Addresses #205, changes semantics of all CASE-s to break on return 0.
=> Fixed lack of return in kobject_read

kernel/Makefile, kernel/bcache.c, kernel/bcache.h, kernel/cdromfs.c, kernel/console.c, kernel/device.c, kernel/device.h, kernel/kevinfs.c, kernel/kshell.c, kernel/list.c, kernel/list.h
First pass at creating a unified buffer cache layer above the device abstraction.
`cdromfs` is now routed through `bcache` but `kevinfs` does direct access right now.
Waiting on fixes #186 before hooking up kevinfs.
=> Unified Buffer Cache

kernel/console.c, kernel/fs.c, kernel/graphics.c, kernel/graphics.h, kernel/kobject.c, kernel/pipe.c, kernel/pipe.h, kernel/process.c, kernel/syscall_handler.c
- Extended reference counting to pipes, graphics, and console.
- Made reference counting more consistent: only delete on count==0, consider <0 to be a no-op.
- kobject now deletes underlying objects consistently.
- pipe open/close -> create/delete
=> Improve Reference Counting

Makefile, include/library/syscalls.h, kernel/kshell.c, kernel/process.c, kernel/syscall_handler.c, kernel/syscall_handler.h, library/syscalls.c, library/user-start.c, user/ball.c, user/clock.c, user/copy.c, user/exectest.c, user/filedescribetest.c, user/forktest.c, user/long.c, user/manager.c, user/mandelbrot.c, user/open.c, user/pipetest.c, user/printer.c, user/procstat.c, user/saver.c, user/shell.c, user/snake.c, user/sysstat.c, user/test.c, user/write.c, user/writebig.c
In response to #233 , I fixed the order of argv and argc in all programs that use them.
The Unix convention is to have argc before argv. However, we have been doing argv before argc.
So, throughout all of the user programs, I switched the order to be argc, argv for their main functions. I also changed the system calls to follow that convention as well. I also changed library/user-start.c
In the kernel, I adjusted systemcall_handler accordingly, and changed process_pass_arguments to push argc after it pushes argv.
I tested it by running user/test.exe with different numbers of arguments.
=> Fix order of argv and argc

kernel/rtc.c, kernel/rtc.h
Made boottime extern in rtc.h, and defined it in rtc.c.  This fixes a linker error
=> Fix multiply defined boottime.

kernel/serial.c
Currently `serial_read` calls `inb` but doesn't return the character. This commit fixes that.
Sorry if I should create an issue instead, but I don't see any way for user programs to access the serial. Is there something I have missed ? (If it doesn't exist, its fine, I can hack on it)
=> Fix serial_read function to actually return the character

kernel/clock.c
Fixed a bug where the clock ticked twice as fast. This commit bumps the frequency (CLICKS_PER_SECOND) to 20, and sets the PIT counter to the correct value.
Closes #288
=> Fix kernel/clock.c to configure PIT properly

kernel/elf.c, kernel/kshell.c, kernel/main.c, kernel/page.c, kernel/pipe.c
By mistake, `elf` was not loading all data sections of programs.  This would show up in errors related to initialization of global structures.
=> elf: Load all sections.

kernel/kernelcore.S, kernel/process.c, kernel/x86.h, user/sysstat.c
Save and restore es, fs, gs segments in interrupts and context switch.
Remove workaround from sysstat for es register.
=> Fix ES Segment Handling

kernel/ata.c, kernel/diskfs.c, kernel/diskfs.h, kernel/kshell.c, kernel/process.c
- Modify ata_wait to use process_yield rather than clock_wait when polling on controller status.  The latter would result in a 1/20s delay on each sub-operation, which was unacceptably slow.
- Several minor fixups to disks to better detect and enforce 26 character name limit.
=> ATA: Fix Slow Operation
